dsn: ${TBLS_DSN}
docPath: docs/design/db/tables

templates:
  md:
    table: "db/tbls/table.md.tmpl"

dict:
  Tables: テーブル
  Description: 概要
  Columns: カラム
  Indexes: インデック
  Constraints: 制約
  Triggers: トリガー
  Relations: ER図
  Name: 名称
  Comment: コメント
  Type: タイプ
  Default: デフォルト値
  Children: 子テーブル
  Parents: 親テーブル
  Definition: 定義
  Table Definition: テーブル定義

er:
  skip: true

disableOutputSchema: true
